# -*- coding: utf-8 -*-
"""
100 Задач уровня Easy (Легкий / 8-7 kyu)
Каждая задача содержит slug, title, desc, starter, tags, fn, tests
"""

def _fib_helper(n):
    a, b = 0, 1
    for _ in range(n):
        a, b = b, a + b
    return a

EASY_TASKS = [
    # 1-10: Базовая арифметика и числа
    {
        'slug': 'sum-of-two-numbers',
        'title': 'Сумма двух чисел',
        'desc': 'Напишите функцию `solution(a, b)`, которая принимает два целых числа и возвращает их сумму.\n\n### Пример:\n* Вход: `2, 3` ➔ Результат: `5`',
        'starter': 'def solution(a, b):\n    # Верните сумму a и b\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda a, b: a + b,
        'tests': [(2, 3), (-5, 10), (0, 0), (100, -50), (999, 1)],
    },
    {
        'slug': 'is-even-number',
        'title': 'Проверка на четность',
        'desc': 'Напишите функцию `solution(n)`, которая возвращает `True`, если число `n` четное, и `False`, если нечетное.\n\n### Пример:\n* Вход: `4` ➔ Результат: `True`\n* Вход: `7` ➔ Результат: `False`',
        'starter': 'def solution(n):\n    # Проверьте, четное ли число n\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda n: n % 2 == 0,
        'tests': [(4,), (7,), (0,), (-2,), (-9,), (1000002,)],
    },
    {
        'slug': 'square-of-number',
        'title': 'Квадрат числа',
        'desc': 'Напишите функцию `solution(n)`, которая возвращает квадрат числа `n`.\n\n### Пример:\n* Вход: `5` ➔ Результат: `25`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda n: n ** 2,
        'tests': [(5,), (-3,), (0,), (12,), (100,)],
    },
    {
        'slug': 'celsius-to-fahrenheit',
        'title': 'Конвертер Цельсий в Фаренгейт',
        'desc': 'Напишите функцию `solution(celsius)`, переводящую температуру из градусов Цельсия в Фаренгейты по формуле: `F = C * 1.8 + 32`.\nОкруглите до 1 знака после запятой.\n\n### Пример:\n* Вход: `0` ➔ Результат: `32.0`\n* Вход: `100` ➔ Результат: `212.0`',
        'starter': 'def solution(celsius):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda c: round(c * 1.8 + 32, 1),
        'tests': [(0,), (100,), (-40,), (36.6,), (25,)],
    },
    {
        'slug': 'perimeter-of-rectangle',
        'title': 'Периметр прямоугольника',
        'desc': 'Напишите функцию `solution(a, b)`, находящую периметр прямоугольника со сторонами `a` и `b` (`2 * (a + b)`).\n\n### Пример:\n* Вход: `5, 4` ➔ Результат: `18`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda a, b: 2 * (a + b),
        'tests': [(5, 4), (10, 20), (1, 1), (100, 50)],
    },
    {
        'slug': 'area-of-rectangle',
        'title': 'Площадь прямоугольника',
        'desc': 'Напишите функцию `solution(a, b)`, возвращающую площадь прямоугольника со сторонами `a` и `b`.\n\n### Пример:\n* Вход: `3, 7` ➔ Результат: `21`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda a, b: a * b,
        'tests': [(3, 7), (10, 10), (5, 0), (25, 4)],
    },
    {
        'slug': 'last-digit-of-number',
        'title': 'Последняя цифра числа',
        'desc': 'Напишите функцию `solution(n)`, возвращающую последнюю цифру неотрицательного числа `n`.\n\n### Пример:\n* Вход: `123` ➔ Результат: `3`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda n: abs(n) % 10,
        'tests': [(123,), (5,), (100,), (987654,), (0,)],
    },
    {
        'slug': 'seconds-to-minutes',
        'title': 'Количество целых минут',
        'desc': 'Напишите функцию `solution(seconds)`, вычисляющую количество полных минут в заданном числе секунд `seconds`.\n\n### Пример:\n* Вход: `130` ➔ Результат: `2`',
        'starter': 'def solution(seconds):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda s: s // 60,
        'tests': [(130,), (60,), (59,), (3600,), (0,)],
    },
    {
        'slug': 'sum-from-one-to-n',
        'title': 'Сумма чисел от 1 до N',
        'desc': 'Напишите функцию `solution(n)`, вычисляющую сумму всех натуральных чисел от 1 до `n` включительно.\n\n### Пример:\n* Вход: `5` ➔ Результат: `15` (1+2+3+4+5)',
        'starter': 'def solution(n):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda n: n * (n + 1) // 2,
        'tests': [(5,), (10,), (1,), (100,), (50,)],
    },
    {
        'slug': 'cube-of-number',
        'title': 'Куб числа',
        'desc': 'Напишите функцию `solution(n)`, возвращающую куб числа `n` (`n ** 3`).\n\n### Пример:\n* Вход: `3` ➔ Результат: `27`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda n: n ** 3,
        'tests': [(3,), (-2,), (0,), (5,), (10,)],
    },

    # 11-20: Простые условия и логика
    {
        'slug': 'is-leap-year',
        'title': 'Високосный год',
        'desc': 'Напишите функцию `solution(year)`, определяющую, является ли год високосным.\nГод високосный, если делится на 4, но не на 100, либо делится на 400.\n\n### Пример:\n* Вход: `2024` ➔ Результат: `True`\n* Вход: `1900` ➔ Результат: `False`',
        'starter': 'def solution(year):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda y: (y % 4 == 0 and y % 100 != 0) or (y % 400 == 0),
        'tests': [(2024,), (1900,), (2000,), (2023,), (2028,)],
    },
    {
        'slug': 'sign-of-number',
        'title': 'Знак числа',
        'desc': 'Напишите функцию `solution(n)`, возвращающую `1` если число положительное, `-1` если отрицательное, и `0` если число равно нулю.\n\n### Пример:\n* Вход: `42` ➔ Результат: `1`\n* Вход: `-15` ➔ Результат: `-1`\n* Вход: `0` ➔ Результат: `0`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['basics'],
        'fn': lambda n: 1 if n > 0 else (-1 if n < 0 else 0),
        'tests': [(42,), (-15,), (0,), (1,), (-100,)],
    },
    {
        'slug': 'max-of-two',
        'title': 'Максимум из двух чисел',
        'desc': 'Напишите функцию `solution(a, b)`, которая возвращает большее из двух чисел без использования встроенной функции `max`.\n\n### Пример:\n* Вход: `10, 20` ➔ Результат: `20`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['basics'],
        'fn': lambda a, b: a if a > b else b,
        'tests': [(10, 20), (5, -5), (7, 7), (-10, -20)],
    },
    {
        'slug': 'min-of-three',
        'title': 'Минимум из трех чисел',
        'desc': 'Напишите функцию `solution(a, b, c)`, возвращающую наименьшее из трех чисел.\n\n### Пример:\n* Вход: `5, 2, 8` ➔ Результат: `2`',
        'starter': 'def solution(a, b, c):\n    pass',
        'tags': ['basics'],
        'fn': lambda a, b, c: min(a, b, c),
        'tests': [(5, 2, 8), (1, 1, 1), (-5, -2, -10), (10, 20, 30)],
    },
    {
        'slug': 'can-form-triangle',
        'title': 'Существование треугольника',
        'desc': 'Напишите функцию `solution(a, b, c)`, которая проверяет, можно ли построить треугольник с длинами сторон `a`, `b`, `c` (сумма любых двух сторон строго больше третьей).\n\n### Пример:\n* Вход: `3, 4, 5` ➔ Результат: `True`\n* Вход: `1, 2, 10` ➔ Результат: `False`',
        'starter': 'def solution(a, b, c):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda a, b, c: a + b > c and a + c > b and b + c > a,
        'tests': [(3, 4, 5), (1, 2, 10), (5, 5, 5), (7, 10, 5), (2, 2, 4)],
    },
    {
        'slug': 'century-from-year',
        'title': 'Определение века по году',
        'desc': 'Напишите функцию `solution(year)`, возвращающую номер века, в котором находится указанный год.\n\n### Пример:\n* Вход: `1905` ➔ Результат: `20`\n* Вход: `1700` ➔ Результат: `17`',
        'starter': 'def solution(year):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda y: (y - 1) // 100 + 1,
        'tests': [(1905,), (1700,), (2000,), (2001,), (85,)],
    },
    {
        'slug': 'is-divisible-by-x-and-y',
        'title': 'Делимость на два числа',
        'desc': 'Напишите функцию `solution(n, x, y)`, проверяющую, делится ли число `n` без остатка на `x` и на `y` одновременно.\n\n### Пример:\n* Вход: `12, 2, 6` ➔ Результат: `True`\n* Вход: `10, 2, 3` ➔ Результат: `False`',
        'starter': 'def solution(n, x, y):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda n, x, y: n % x == 0 and n % y == 0,
        'tests': [(12, 2, 6), (10, 2, 3), (100, 5, 10), (45, 9, 5)],
    },
    {
        'slug': 'absolute-difference',
        'title': 'Модуль разности',
        'desc': 'Напишите функцию `solution(a, b)`, возвращающую абсолютную разность двух чисел `|a - b|`.\n\n### Пример:\n* Вход: `5, 12` ➔ Результат: `7`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda a, b: abs(a - b),
        'tests': [(5, 12), (12, 5), (-3, 7), (0, 0)],
    },
    {
        'slug': 'sum-of-digits',
        'title': 'Сумма цифр числа',
        'desc': 'Напишите функцию `solution(n)`, находящую сумму всех цифр целого положительного числа `n`.\n\n### Пример:\n* Вход: `1234` ➔ Результат: `10` (1+2+3+4)',
        'starter': 'def solution(n):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda n: sum(int(d) for d in str(abs(n))),
        'tests': [(1234,), (905,), (7,), (9999,), (100000,)],
    },
    {
        'slug': 'count-digits-in-number',
        'title': 'Количество цифр в числе',
        'desc': 'Напишите функцию `solution(n)`, определяющую количество цифр в числе `n`.\n\n### Пример:\n* Вход: `54321` ➔ Результат: `5`\n* Вход: `0` ➔ Результат: `1`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['basics', 'math'],
        'fn': lambda n: len(str(abs(n))),
        'tests': [(54321,), (0,), (9,), (-456,), (1000000,)],
    },

    # 21-35: Строки (базовые операции)
    {
        'slug': 'string-length',
        'title': 'Длина строки',
        'desc': 'Напишите функцию `solution(s)`, возвращающую длину переданной строки `s`.\n\n### Пример:\n* Вход: `"Python"` ➔ Результат: `6`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings', 'basics'],
        'fn': lambda s: len(s),
        'tests': [("Python",), ("",), ("Hello World!",), ("12345",)],
    },
    {
        'slug': 'reverse-string',
        'title': 'Разворот строки',
        'desc': 'Напишите функцию `solution(s)`, которая разворачивает строку задом наперед.\n\n### Пример:\n* Вход: `"code"` ➔ Результат: `"edoc"`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: s[::-1],
        'tests': [("code",), ("racecar",), ("a",), ("",), ("SmartCode",)],
    },
    {
        'slug': 'is-palindrome-string',
        'title': 'Проверка палиндрома',
        'desc': 'Напишите функцию `solution(s)`, проверяющую, является ли строка палиндромом (читается одинаково слева направо и справа налево, без учета регистра).\n\n### Пример:\n* Вход: `"Радар"` ➔ Результат: `True`\n* Вход: `"Привет"` ➔ Результат: `False`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: s.lower() == s.lower()[::-1],
        'tests': [("Радар",), ("Привет",), ("Madam",), ("a",), ("abacaba",)],
    },
    {
        'slug': 'count-vowels',
        'title': 'Подсчет гласных букв',
        'desc': 'Напишите функцию `solution(s)`, возвращающую количество английских гласных букв (`a, e, i, o, u`) в строке без учета регистра.\n\n### Пример:\n* Вход: `"hello world"` ➔ Результат: `3` (e, o, o)',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: sum(1 for c in s.lower() if c in 'aeiou'),
        'tests': [("hello world",), ("PYTHON",), ("xyz",), ("aeiouAEIOU",), ("",)],
    },
    {
        'slug': 'repeat-string',
        'title': 'Повторение строки',
        'desc': 'Напишите функцию `solution(s, n)`, которая повторяет строку `s` ровно `n` раз.\n\n### Пример:\n* Вход: `"ha", 3` ➔ Результат: `"hahaha"`',
        'starter': 'def solution(s, n):\n    pass',
        'tags': ['strings', 'basics'],
        'fn': lambda s, n: s * n,
        'tests': [("ha", 3), ("*", 5), ("abc", 0), ("code", 1)],
    },
    {
        'slug': 'first-and-last-char',
        'title': 'Удаление первого и последнего символа',
        'desc': 'Напишите функцию `solution(s)`, возвращающую строку `s` без первого и последнего символа. Если длина строки <= 2, верните пустую строку `""`.\n\n### Пример:\n* Вход: `"eloquent"` ➔ Результат: `"loquen"`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: s[1:-1] if len(s) > 2 else "",
        'tests': [("eloquent",), ("ok",), ("a",), ("xyz",), ("SmartCode",)],
    },
    {
        'slug': 'count-words-in-sentence',
        'title': 'Подсчет количества слов',
        'desc': 'Напишите функцию `solution(sentence)`, подсчитывающую количество слов в предложении, разделенных пробелами.\n\n### Пример:\n* Вход: `"Учимся программировать на Python"` ➔ Результат: `4`',
        'starter': 'def solution(sentence):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: len(s.split()),
        'tests': [("Учимся программировать на Python",), ("Один",), ("",), ("   много    пробелов   ",)],
    },
    {
        'slug': 'capitalize-words',
        'title': 'Каждое слово с заглавной буквы',
        'desc': 'Напишите функцию `solution(s)`, переводящую первую букву каждого слова в верхний регистр (аналог `.title()`).\n\n### Пример:\n* Вход: `"hello smart code"` ➔ Результат: `"Hello Smart Code"`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: s.title(),
        'tests': [("hello smart code",), ("python language",), ("a",), ("test case",)],
    },
    {
        'slug': 'remove-all-spaces',
        'title': 'Удаление всех пробелов',
        'desc': 'Напишите функцию `solution(s)`, которая удаляет все пробелы из переданной строки.\n\n### Пример:\n* Вход: `"8 j 8   mBliB8g  imjB8B8  jl  B"` ➔ Результат: `"8j8mBliB8gimjB8B8jlB"`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: s.replace(' ', ''),
        'tests': [("8 j 8   mBliB8g",), ("  a b c  ",), ("nospace",), ("",)],
    },
    {
        'slug': 'mask-credit-card',
        'title': 'Маскирование номера карты',
        'desc': 'Напишите функцию `solution(cc)`, которая заменяет все символы строки, кроме последних 4, символом `#`. Если длина <= 4, строка остается без изменений.\n\n### Пример:\n* Вход: `"1234567890123456"` ➔ Результат: `"############3456"`\n* Вход: `"123"` ➔ Результат: `"123"`',
        'starter': 'def solution(cc):\n    pass',
        'tags': ['strings'],
        'fn': lambda cc: '#' * (len(cc) - 4) + cc[-4:] if len(cc) > 4 else cc,
        'tests': [("1234567890123456",), ("123",), ("4111222233334444",), ("1",), ("",)],
    },
    {
        'slug': 'swap-case-string',
        'title': 'Инверсия регистра букв',
        'desc': 'Напишите функцию `solution(s)`, меняющую регистр каждого символа на противоположный (строчные в заглавные, заглавные в строчные).\n\n### Пример:\n* Вход: `"Hello World"` ➔ Результат: `"hELLO wORLD"`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: s.swapcase(),
        'tests': [("Hello World",), ("PYTHON",), ("python",), ("123!@#",)],
    },
    {
        'slug': 'remove-vowels-from-string',
        'title': 'Удаление всех гласных букв',
        'desc': 'Напишите функцию `solution(s)`, удаляющую все английские гласные (`a, e, i, o, u, A, E, I, O, U`) из строки.\n\n### Пример:\n* Вход: `"This website is awesome"` ➔ Результат: `"Ths wbst s wsm"`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: ''.join(c for c in s if c not in 'aeiouAEIOU'),
        'tests': [("This website is awesome",), ("HELLO",), ("aeiou",), ("rhythm",)],
    },
    {
        'slug': 'ends-with-string',
        'title': 'Проверка окончания строки',
        'desc': 'Напишите функцию `solution(s, ending)`, проверяющую, заканчивается ли строка `s` подстрокой `ending`.\n\n### Пример:\n* Вход: `"abc", "bc"` ➔ Результат: `True`\n* Вход: `"abc", "d"` ➔ Результат: `False`',
        'starter': 'def solution(s, ending):\n    pass',
        'tags': ['strings'],
        'fn': lambda s, e: s.endswith(e),
        'tests': [("abc", "bc"), ("abc", "d"), ("samurai", "ai"), ("ninja", "ja"), ("test", "")],
    },
    {
        'slug': 'count-char-occurrences',
        'title': 'Подсчет вхождений символа',
        'desc': 'Напишите функцию `solution(s, char)`, подсчитывающую, сколько раз символ `char` встречается в строке `s`.\n\n### Пример:\n* Вход: `"banana", "a"` ➔ Результат: `3`',
        'starter': 'def solution(s, char):\n    pass',
        'tags': ['strings'],
        'fn': lambda s, c: s.count(c),
        'tests': [("banana", "a"), ("hello", "l"), ("python", "z"), ("", "a")],
    },
    {
        'slug': 'truncate-string',
        'title': 'Усечение строки с многоточием',
        'desc': 'Напишите функцию `solution(s, max_len)`, которая, если длина строки больше `max_len`, обрезает ее до `max_len` символов и добавляет в конец `...`. Иначе возвращает исходную строку.\n\n### Пример:\n* Вход: `"Hello World", 5` ➔ Результат: `"Hello..."`',
        'starter': 'def solution(s, max_len):\n    pass',
        'tags': ['strings'],
        'fn': lambda s, m: s[:m] + "..." if len(s) > m else s,
        'tests': [("Hello World", 5), ("Hi", 10), ("SmartCode", 9), ("Python", 3)],
    },

    # 36-50: Списки и массивы (базовые)
    {
        'slug': 'sum-of-array-elements',
        'title': 'Сумма элементов списка',
        'desc': 'Напишите функцию `solution(nums)`, возвращающую сумму всех чисел в списке. Если список пустой, верните `0`.\n\n### Пример:\n* Вход: `[1, 2, 3, 4, 5]` ➔ Результат: `15`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays', 'basics'],
        'fn': lambda nums: sum(nums),
        'tests': [([1, 2, 3, 4, 5],), ([],), ([-1, -2, 3],), ([100],)],
    },
    {
        'slug': 'find-maximum-in-list',
        'title': 'Максимум в списке',
        'desc': 'Напишите функцию `solution(nums)`, находящую максимальное число в непустом списке чисел.\n\n### Пример:\n* Вход: `[4, 6, 2, 1, 9, 63, -134, 566]` ➔ Результат: `566`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums: max(nums),
        'tests': [([4, 6, 2, 1, 9, 63, -134, 566],), ([5],), ([-10, -5, -20],), ([1, 2, 3],)],
    },
    {
        'slug': 'find-minimum-in-list',
        'title': 'Минимум в списке',
        'desc': 'Напишите функцию `solution(nums)`, находящую минимальное число в непустом списке чисел.\n\n### Пример:\n* Вход: `[7, 3, 9, 1, 4]` ➔ Результат: `1`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums: min(nums),
        'tests': [([7, 3, 9, 1, 4],), ([42],), ([-100, 0, 100],), ([9, 8, 7],)],
    },
    {
        'slug': 'filter-even-numbers',
        'title': 'Фильтрация четных чисел',
        'desc': 'Напишите функцию `solution(nums)`, которая возвращает новый список, содержащий только четные числа из исходного списка в том же порядке.\n\n### Пример:\n* Вход: `[1, 2, 3, 4, 5, 6]` ➔ Результат: `[2, 4, 6]`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums: [x for x in nums if x % 2 == 0],
        'tests': [([1, 2, 3, 4, 5, 6],), ([1, 3, 5],), ([2, 4, 8],), ([],)],
    },
    {
        'slug': 'average-of-list',
        'title': 'Среднее арифметическое списка',
        'desc': 'Напишите функцию `solution(nums)`, вычисляющую среднее арифметическое чисел в списке с округлением до 2 знаков после запятой. Для пустого списка верните `0`.\n\n### Пример:\n* Вход: `[1, 2, 3, 4, 5]` ➔ Результат: `3.0`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays', 'math'],
        'fn': lambda nums: round(sum(nums) / len(nums), 2) if nums else 0,
        'tests': [([1, 2, 3, 4, 5],), ([10, 20, 30],), ([1, 2],), ([],), ([7],)],
    },
    {
        'slug': 'reverse-list',
        'title': 'Разворот списка',
        'desc': 'Напишите функцию `solution(lst)`, которая возвращает элементы списка в обратном порядке.\n\n### Пример:\n* Вход: `[1, 2, 3, 4]` ➔ Результат: `[4, 3, 2, 1]`',
        'starter': 'def solution(lst):\n    pass',
        'tags': ['arrays'],
        'fn': lambda lst: lst[::-1],
        'tests': [([1, 2, 3, 4],), (["a", "b", "c"],), ([],), ([1],)],
    },
    {
        'slug': 'count-positives-sum-negatives',
        'title': 'Подсчет положительных и сумма отрицательных',
        'desc': 'Напишите функцию `solution(nums)`, возвращающую список из двух чисел: `[количество положительных чисел (>0), сумма отрицательных чисел (<0)]`. Если список пуст, верните `[0, 0]`.\n\n### Пример:\n* Вход: `[1, 2, 3, 4, -5, -6]` ➔ Результат: `[4, -11]`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums: [sum(1 for x in nums if x > 0), sum(x for x in nums if x < 0)],
        'tests': [([1, 2, 3, 4, -5, -6],), ([],), ([1, 2, 3],), ([-1, -2],)],
    },
    {
        'slug': 'multiply-list-by-factor',
        'title': 'Умножение всех элементов на коэффициент',
        'desc': 'Напишите функцию `solution(nums, k)`, которая умножает каждый элемент списка `nums` на число `k`.\n\n### Пример:\n* Вход: `[1, 2, 3], 2` ➔ Результат: `[2, 4, 6]`',
        'starter': 'def solution(nums, k):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums, k: [x * k for x in nums],
        'tests': [([1, 2, 3], 2), ([-1, 0, 5], 3), ([], 10), ([4, 8], 0)],
    },
    {
        'slug': 'remove-duplicates-keep-order',
        'title': 'Удаление дубликатов с сохранением порядка',
        'desc': 'Напишите функцию `solution(lst)`, удаляющую повторяющиеся элементы из списка с сохранением исходного порядка первого появления.\n\n### Пример:\n* Вход: `[1, 2, 2, 3, 1, 4]` ➔ Результат: `[1, 2, 3, 4]`',
        'starter': 'def solution(lst):\n    pass',
        'tags': ['arrays'],
        'fn': lambda lst: list(dict.fromkeys(lst)),
        'tests': [([1, 2, 2, 3, 1, 4],), (["a", "b", "a"],), ([],), ([5, 5, 5],)],
    },
    {
        'slug': 'check-element-in-list',
        'title': 'Проверка наличия элемента',
        'desc': 'Напишите функцию `solution(lst, target)`, проверяющую, содержится ли элемент `target` в списке `lst` (`True` / `False`).\n\n### Пример:\n* Вход: `[1, 5, 9], 5` ➔ Результат: `True`\n* Вход: `[1, 5, 9], 4` ➔ Результат: `False`',
        'starter': 'def solution(lst, target):\n    pass',
        'tags': ['arrays', 'basics'],
        'fn': lambda lst, t: t in lst,
        'tests': [([1, 5, 9], 5), ([1, 5, 9], 4), ([], 1), (["cat", "dog"], "cat")],
    },
    {
        'slug': 'find-index-of-element',
        'title': 'Поиск индекса первого вхождения',
        'desc': 'Напишите функцию `solution(lst, target)`, возвращающую индекс первого вхождения `target` в `lst`. Если элемент не найден, верните `-1`.\n\n### Пример:\n* Вход: `[10, 20, 30, 20], 20` ➔ Результат: `1`\n* Вход: `[1, 2, 3], 99` ➔ Результат: `-1`',
        'starter': 'def solution(lst, target):\n    pass',
        'tags': ['arrays', 'search'],
        'fn': lambda lst, t: lst.index(t) if t in lst else -1,
        'tests': [([10, 20, 30, 20], 20), ([1, 2, 3], 99), ([], 5), (["a", "b"], "a")],
    },
    {
        'slug': 'difference-max-min-list',
        'title': 'Разница между максимумом и минимумом',
        'desc': 'Напишите функцию `solution(nums)`, находящую разность между наибольшим и наименьшим числом в списке.\n\n### Пример:\n* Вход: `[10, 3, 5, 6]` ➔ Результат: `7` (10 - 3)',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays', 'math'],
        'fn': lambda nums: max(nums) - min(nums),
        'tests': [([10, 3, 5, 6],), ([5],), ([-10, 10],), ([1, 1, 1],)],
    },
    {
        'slug': 'cumulative-sum-list',
        'title': 'Кумулятивная сумма списка',
        'desc': 'Напишите функцию `solution(nums)`, возвращающую список кумулятивных сумм (`[a[0], a[0]+a[1], a[0]+a[1]+a[2], ...]`)\n\n### Пример:\n* Вход: `[1, 2, 3, 4]` ➔ Результат: `[1, 3, 6, 10]`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums: [sum(nums[:i+1]) for i in range(len(nums))],
        'tests': [([1, 2, 3, 4],), ([5],), ([],), ([1, 1, 1, 1],)],
    },
    {
        'slug': 'is-list-sorted-ascending',
        'title': 'Проверка списка на отсортированность',
        'desc': 'Напишите функцию `solution(nums)`, проверяющую, отсортирован ли список по возрастанию (неубыванию).\n\n### Пример:\n* Вход: `[1, 2, 2, 5]` ➔ Результат: `True`\n* Вход: `[1, 3, 2]` ➔ Результат: `False`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums: nums == sorted(nums),
        'tests': [([1, 2, 2, 5],), ([1, 3, 2],), ([],), ([7],), ([5, 4, 3],)],
    },
    {
        'slug': 'merge-two-sorted-lists-simple',
        'title': 'Объединение двух отсортированных списков',
        'desc': 'Напишите функцию `solution(a, b)`, которая принимает два списка и возвращает один отсортированный список всех элементов.\n\n### Пример:\n* Вход: `[1, 3, 5], [2, 4, 6]` ➔ Результат: `[1, 2, 3, 4, 5, 6]`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['arrays'],
        'fn': lambda a, b: sorted(a + b),
        'tests': [([1, 3, 5], [2, 4, 6]), ([], [1, 2]), ([5, 10], []), ([3], [1])],
    },

    # 51-65: Словари и множества
    {
        'slug': 'char-frequency-dict',
        'title': 'Частота символов в строке',
        'desc': 'Напишите функцию `solution(s)`, возвращающую словарь, где ключи — символы строки, а значения — сколько раз они встречаются.\n\n### Пример:\n* Вход: `"aba"` ➔ Результат: `{"a": 2, "b": 1}`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['dicts', 'strings'],
        'fn': lambda s: {c: s.count(c) for c in s},
        'tests': [("aba",), ("hello",), ("",), ("mississippi",)],
    },
    {
        'slug': 'key-with-max-value',
        'title': 'Ключ с максимальным значением',
        'desc': 'Напишите функцию `solution(d)`, возвращающую ключ с наибольшим числовым значением из словаря `d`. Словарь гарантированно не пуст.\n\n### Пример:\n* Вход: `{"a": 10, "b": 35, "c": 5}` ➔ Результат: `"b"`',
        'starter': 'def solution(d):\n    pass',
        'tags': ['dicts'],
        'fn': lambda d: max(d, key=d.get),
        'tests': [({"a": 10, "b": 35, "c": 5},), ({"x": 100},), ({"p": -5, "q": -1},)],
    },
    {
        'slug': 'invert-dictionary',
        'title': 'Инвертирование словаря',
        'desc': 'Напишите функцию `solution(d)`, меняющую местами ключи и значения в словаре. Все значения гарантированно уникальны.\n\n### Пример:\n* Вход: `{"a": 1, "b": 2}` ➔ Результат: `{1: "a", 2: "b"}`',
        'starter': 'def solution(d):\n    pass',
        'tags': ['dicts'],
        'fn': lambda d: {v: k for k, v in d.items()},
        'tests': [({"a": 1, "b": 2},), ({},), ({"apple": "red", "banana": "yellow"},)],
    },
    {
        'slug': 'common-elements-in-lists',
        'title': 'Общие элементы двух списков',
        'desc': 'Напишите функцию `solution(a, b)`, возвращающую отсортированный список уникальных элементов, которые присутствуют в обоих списках.\n\n### Пример:\n* Вход: `[1, 2, 3], [2, 3, 4]` ➔ Результат: `[2, 3]`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['dicts', 'arrays'],
        'fn': lambda a, b: sorted(list(set(a) & set(b))),
        'tests': [([1, 2, 3], [2, 3, 4]), ([1, 2], [3, 4]), ([], [1]), ([5, 5, 5], [5, 5])],
    },
    {
        'slug': 'count-unique-elements',
        'title': 'Количество уникальных элементов',
        'desc': 'Напишите функцию `solution(lst)`, возвращающую число уникальных элементов в списке.\n\n### Пример:\n* Вход: `[1, 2, 2, 3, 3, 3]` ➔ Результат: `3`',
        'starter': 'def solution(lst):\n    pass',
        'tags': ['dicts', 'arrays'],
        'fn': lambda lst: len(set(lst)),
        'tests': [([1, 2, 2, 3, 3, 3],), ([],), ([42],), (["a", "b", "c", "a"],)],
    },
    {
        'slug': 'merge-two-dictionaries',
        'title': 'Слияние двух словарей',
        'desc': 'Напишите функцию `solution(d1, d2)`, объединяющую два словаря. При совпадении ключей значение из `d2` перезаписывает `d1`.\n\n### Пример:\n* Вход: `{"a": 1}, {"b": 2, "a": 3}` ➔ Результат: `{"a": 3, "b": 2}`',
        'starter': 'def solution(d1, d2):\n    pass',
        'tags': ['dicts'],
        'fn': lambda d1, d2: {**d1, **d2},
        'tests': [({"a": 1}, {"b": 2, "a": 3}), ({}, {"x": 10}), ({"a": 1}, {})],
    },
    {
        'slug': 'sum-dictionary-values',
        'title': 'Сумма значений словаря',
        'desc': 'Напишите функцию `solution(d)`, возвращающую сумму всех числовых значений словаря `d`.\n\n### Пример:\n* Вход: `{"apple": 50, "banana": 30}` ➔ Результат: `80`',
        'starter': 'def solution(d):\n    pass',
        'tags': ['dicts', 'math'],
        'fn': lambda d: sum(d.values()),
        'tests': [({"apple": 50, "banana": 30},), ({},), ({"x": -10, "y": 10},)],
    },
    {
        'slug': 'filter-dict-by-threshold',
        'title': 'Фильтрация словаря по порогу',
        'desc': 'Напишите функцию `solution(d, min_val)`, возвращающую новый словарь только с теми элементами, чьи значения `>= min_val`.\n\n### Пример:\n* Вход: `{"a": 5, "b": 12, "c": 3}, 10` ➔ Результат: `{"b": 12}`',
        'starter': 'def solution(d, min_val):\n    pass',
        'tags': ['dicts'],
        'fn': lambda d, m: {k: v for k, v in d.items() if v >= m},
        'tests': [({"a": 5, "b": 12, "c": 3}, 10), ({"x": 1}, 5), ({}, 0)],
    },
    {
        'slug': 'word-lengths-dict',
        'title': 'Длины слов в словаре',
        'desc': 'Напишите функцию `solution(words)`, которая принимает список слов и возвращает словарь вида `{слово: длина}`.\n\n### Пример:\n* Вход: `["cat", "apple"]` ➔ Результат: `{"cat": 3, "apple": 5}`',
        'starter': 'def solution(words):\n    pass',
        'tags': ['dicts', 'strings'],
        'fn': lambda words: {w: len(w) for w in words},
        'tests': [(["cat", "apple"],), ([],), (["Python", "Code", "AI"],)],
    },
    {
        'slug': 'is-subset-list',
        'title': 'Проверка на подмножество',
        'desc': 'Напишите функцию `solution(a, b)`, проверяющую, являются ли все элементы списка `a` частью списка `b`.\n\n### Пример:\n* Вход: `[1, 2], [1, 2, 3, 4]` ➔ Результат: `True`\n* Вход: `[1, 5], [1, 2, 3]` ➔ Результат: `False`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['dicts', 'arrays'],
        'fn': lambda a, b: set(a).issubset(set(b)),
        'tests': [([1, 2], [1, 2, 3, 4]), ([1, 5], [1, 2, 3]), ([], [1, 2]), ([1], [1])],
    },

    # 61-70: Математика, паттерны и формулы
    {
        'slug': 'factorial-number',
        'title': 'Факториал числа',
        'desc': 'Напишите функцию `solution(n)`, возвращающую факториал неотрицательного числа `n` (`n!`).\nДля `0` факториал равен `1`.\n\n### Пример:\n* Вход: `5` ➔ Результат: `120`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math', 'basics'],
        'fn': lambda n: 1 if n <= 1 else (lambda f, x: f(f, x))(lambda self, k: 1 if k <= 1 else k * self(self, k - 1), n),
        'tests': [(5,), (0,), (1,), (6,), (10,)],
    },
    {
        'slug': 'fibonacci-number',
        'title': 'N-е число Фибоначчи',
        'desc': 'Напишите функцию `solution(n)`, возвращающую `n`-е число Фибоначчи (нумерация с 0: `F(0)=0, F(1)=1, F(2)=1, F(3)=2, ...`).\n\n### Пример:\n* Вход: `6` ➔ Результат: `8`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math', 'recursion'],
        'fn': _fib_helper,
        'tests': [(0,), (1,), (6,), (10,), (15,)],
    },
    {
        'slug': 'gcd-two-numbers',
        'title': 'Наибольший общий делитель (НОД)',
        'desc': 'Напишите функцию `solution(a, b)`, возвращающую наибольший общий делитель двух положительных чисел по алгоритму Евклида.\n\n### Пример:\n* Вход: `48, 18` ➔ Результат: `6`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['math'],
        'fn': lambda a, b: (lambda f: f(f, a, b))(lambda self, x, y: x if y == 0 else self(self, y, x % y)),
        'tests': [(48, 18), (10, 5), (7, 13), (100, 25), (1071, 462)],
    },
    {
        'slug': 'lcm-two-numbers',
        'title': 'Наименьшее общее кратное (НОК)',
        'desc': 'Напишите функцию `solution(a, b)`, находящую наименьшее общее кратное двух чисел `(a * b) // НОД(a, b)`.\n\n### Пример:\n* Вход: `4, 6` ➔ Результат: `12`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['math'],
        'fn': lambda a, b: (a * b) // (lambda f: f(f, a, b))(lambda self, x, y: x if y == 0 else self(self, y, x % y)),
        'tests': [(4, 6), (5, 7), (10, 20), (21, 6)],
    },
    {
        'slug': 'is-prime-number',
        'title': 'Проверка на простое число',
        'desc': 'Напишите функцию `solution(n)`, возвращающую `True`, если натуральное число `n > 1` является простым, и `False` в противном случае.\n\n### Пример:\n* Вход: `7` ➔ Результат: `True`\n* Вход: `4` ➔ Результат: `False`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math'],
        'fn': lambda n: n > 1 and all(n % i != 0 for i in range(2, int(n**0.5) + 1)),
        'tests': [(7,), (4,), (1,), (2,), (13,), (25,), (97,)],
    },
    {
        'slug': 'power-of-two-check',
        'title': 'Проверка на степень двойки',
        'desc': 'Напишите функцию `solution(n)`, возвращающую `True`, если целое число `n > 0` является степенью двойки (1, 2, 4, 8, 16...).\n\n### Пример:\n* Вход: `16` ➔ Результат: `True`\n* Вход: `18` ➔ Результат: `False`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math'],
        'fn': lambda n: n > 0 and (n & (n - 1)) == 0,
        'tests': [(16,), (18,), (1,), (2,), (1024,), (0,), (-8,)],
    },
    {
        'slug': 'count-primes-up-to-n',
        'title': 'Количество простых чисел до N',
        'desc': 'Напишите функцию `solution(n)`, подсчитывающую количество простых чисел, строго меньших числа `n`.\n\n### Пример:\n* Вход: `10` ➔ Результат: `4` (2, 3, 5, 7)',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math'],
        'fn': lambda n: sum(1 for x in range(2, n) if all(x % i != 0 for i in range(2, int(x**0.5) + 1))),
        'tests': [(10,), (2,), (20,), (1,), (50,)],
    },
    {
        'slug': 'hypotenuse-triangle',
        'title': 'Длина гипотенузы',
        'desc': 'Напишите функцию `solution(a, b)`, находящую длину гипотенузы прямоугольного треугольника с катетами `a` и `b` по теореме Пифагора (округлить до 2 знаков).\n\n### Пример:\n* Вход: `3, 4` ➔ Результат: `5.0`',
        'starter': 'def solution(a, b):\n    pass',
        'tags': ['math'],
        'fn': lambda a, b: round((a**2 + b**2)**0.5, 2),
        'tests': [(3, 4), (5, 12), (1, 1), (6, 8)],
    },
    {
        'slug': 'sum-of-squares',
        'title': 'Сумма квадратов первых N чисел',
        'desc': 'Напишите функцию `solution(n)`, находящую сумму квадратов чисел от 1 до `n` (`1^2 + 2^2 + ... + n^2`).\n\n### Пример:\n* Вход: `3` ➔ Результат: `14` (1+4+9)',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math'],
        'fn': lambda n: n * (n + 1) * (2 * n + 1) // 6,
        'tests': [(3,), (5,), (1,), (10,)],
    },
    {
        'slug': 'is-lucky-ticket',
        'title': 'Счастливый шестизначный билет',
        'desc': 'Напишите функцию `solution(ticket)`, проверяющую, является ли шестизначный номер билета (строка) счастливым (сумма первых трех цифр равна сумме последних трех).\n\n### Пример:\n* Вход: `"123321"` ➔ Результат: `True`\n* Вход: `"123456"` ➔ Результат: `False`',
        'starter': 'def solution(ticket):\n    pass',
        'tags': ['strings', 'math'],
        'fn': lambda t: sum(int(c) for c in t[:3]) == sum(int(c) for c in t[3:]),
        'tests': [("123321",), ("123456",), ("000000",), ("456654",)],
    },

    # 71-80: Разные практические микро-задачи
    {
        'slug': 'fizz-buzz-single',
        'title': 'FizzBuzz для одного числа',
        'desc': 'Напишите функцию `solution(n)`, возвращающую:\n* `"FizzBuzz"` если число делится на 3 и 5,\n* `"Fizz"` если делится на 3,\n* `"Buzz"` если делится на 5,\n* иначе само число в виде строки `str(n)`.\n\n### Пример:\n* Вход: `15` ➔ Результат: `"FizzBuzz"`\n* Вход: `9` ➔ Результат: `"Fizz"`\n* Вход: `7` ➔ Результат: `"7"`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['basics'],
        'fn': lambda n: "FizzBuzz" if n % 15 == 0 else ("Fizz" if n % 3 == 0 else ("Buzz" if n % 5 == 0 else str(n))),
        'tests': [(15,), (9,), (10,), (7,), (30,)],
    },
    {
        'slug': 'rock-paper-scissors-eval',
        'title': 'Камень, Ножницы, Бумага',
        'desc': 'Напишите функцию `solution(p1, p2)`, определяющую победителя в игре.\nВарианты: `"rock"`, `"scissors"`, `"paper"`.\nВозвращает: `"p1"` если победил игрок 1, `"p2"` если победил игрок 2, `"draw"` при ничьей.\n\n### Пример:\n* Вход: `"rock", "scissors"` ➔ Результат: `"p1"`',
        'starter': 'def solution(p1, p2):\n    pass',
        'tags': ['basics'],
        'fn': lambda p1, p2: "draw" if p1 == p2 else ("p1" if (p1, p2) in [("rock", "scissors"), ("scissors", "paper"), ("paper", "rock")] else "p2"),
        'tests': [("rock", "scissors"), ("scissors", "rock"), ("paper", "paper"), ("scissors", "paper")],
    },
    {
        'slug': 'traffic-light-next',
        'title': 'Следующий сигнал светофора',
        'desc': 'Напишите функцию `solution(current)`, которая принимает текущий сигнал светофора (`"green"`, `"yellow"`, `"red"`) и возвращает следующий: `green ➔ yellow ➔ red ➔ green`.\n\n### Пример:\n* Вход: `"green"` ➔ Результат: `"yellow"`',
        'starter': 'def solution(current):\n    pass',
        'tags': ['basics'],
        'fn': lambda c: {"green": "yellow", "yellow": "red", "red": "green"}.get(c, ""),
        'tests': [("green",), ("yellow",), ("red",)],
    },
    {
        'slug': 'sum-multiples-of-3-or-5',
        'title': 'Сумма кратных 3 или 5 до N',
        'desc': 'Напишите функцию `solution(n)`, возвращающую сумму всех натуральных чисел строго меньше `n`, которые кратны 3 или 5.\n\n### Пример:\n* Вход: `10` ➔ Результат: `23` (3+5+6+9)',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math'],
        'fn': lambda n: sum(x for x in range(n) if x % 3 == 0 or x % 5 == 0),
        'tests': [(10,), (20,), (5,), (1,)],
    },
    {
        'slug': 'quarter-of-year',
        'title': 'Квартал года по месяцу',
        'desc': 'Напишите функцию `solution(month)`, возвращающую номер квартала (1-4) для заданного месяца (1-12).\n\n### Пример:\n* Вход: `5` ➔ Результат: `2`',
        'starter': 'def solution(month):\n    pass',
        'tags': ['basics'],
        'fn': lambda m: (m - 1) // 3 + 1,
        'tests': [(1,), (5,), (9,), (12,), (3,)],
    },
    {
        'slug': 'dna-to-rna-conversion',
        'title': 'Транскрипция ДНК в РНК',
        'desc': 'Напишите функцию `solution(dna)`, которая переводит цепочку ДНК в РНК, заменяя все тимины `T` на урацилы `U`.\n\n### Пример:\n* Вход: `"GCAT"` ➔ Результат: `"GCAU"`',
        'starter': 'def solution(dna):\n    pass',
        'tags': ['strings'],
        'fn': lambda dna: dna.replace('T', 'U'),
        'tests': [("GCAT",), ("TTTT",), ("GACCGCCG",), ("",)],
    },
    {
        'slug': 'remove-exclamation-marks',
        'title': 'Удаление восклицательных знаков',
        'desc': 'Напишите функцию `solution(s)`, удаляющую все знаки `!` из строки `s`.\n\n### Пример:\n* Вход: `"Hello! World!"` ➔ Результат: `"Hello World"`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: s.replace('!', ''),
        'tests': [("Hello! World!",), ("!!!",), ("Hi",), ("",)],
    },
    {
        'slug': 'string-to-number-safe',
        'title': 'Преобразование строки в целое число',
        'desc': 'Напишите функцию `solution(s)`, преобразующую строку в число (`int`).\n\n### Пример:\n* Вход: `"-123"` ➔ Результат: `-123`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['basics'],
        'fn': lambda s: int(s),
        'tests': [("123",), ("-45",), ("0",), ("999999",)],
    },
    {
        'slug': 'bool-to-word',
        'title': 'Логическое значение в слово',
        'desc': 'Напишите функцию `solution(b)`, возвращающую `"Yes"` для `True` и `"No"` для `False`.\n\n### Пример:\n* Вход: `True` ➔ Результат: `"Yes"`',
        'starter': 'def solution(b):\n    pass',
        'tags': ['basics'],
        'fn': lambda b: "Yes" if b else "No",
        'tests': [(True,), (False,)],
    },
    {
        'slug': 'double-char-in-string',
        'title': 'Удвоение каждого символа',
        'desc': 'Напишите функцию `solution(s)`, которая возвращает строку, где каждый символ повторен дважды.\n\n### Пример:\n* Вход: `"String"` ➔ Результат: `"SSttrriinngg"`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: ''.join(c * 2 for c in s),
        'tests': [("String",), ("Hello World",), ("1234!_ ",), ("",)],
    },

    # 81-100: Дополнительные алгоритмические основы
    {
        'slug': 'second-largest-element',
        'title': 'Второй по величине элемент',
        'desc': 'Напишите функцию `solution(nums)`, находящую второй наибольший уникальный элемент в списке. В списке гарантированно есть минимум 2 уникальных элемента.\n\n### Пример:\n* Вход: `[10, 20, 4, 45, 99]` ➔ Результат: `45`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays', 'search'],
        'fn': lambda nums: sorted(set(nums))[-2],
        'tests': [([10, 20, 4, 45, 99],), ([1, 2, 2, 3],), ([5, 10],), ([-10, -5, -20],)],
    },
    {
        'slug': 'count-occurences-of-max',
        'title': 'Количество максимальных элементов',
        'desc': 'Напишите функцию `solution(nums)`, подсчитывающую, сколько раз в списке встречается максимальный элемент.\n\n### Пример:\n* Вход: `[3, 2, 3, 1, 3]` ➔ Результат: `3` (число 3 встречается 3 раза)',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums: nums.count(max(nums)),
        'tests': [([3, 2, 3, 1, 3],), ([5],), ([1, 2, 3, 4],), ([7, 7, 7],)],
    },
    {
        'slug': 'alternate-capitalization',
        'title': 'Чередование регистра',
        'desc': 'Напишите функцию `solution(s)`, которая переводит четные индексы в верхний регистр, а нечетные — в нижний.\n\n### Пример:\n* Вход: `"abcdef"` ➔ Результат: `"AbCdEf"`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: ''.join(c.upper() if i % 2 == 0 else c.lower() for i, c in enumerate(s)),
        'tests': [("abcdef",), ("hello",), ("",), ("CODE",)],
    },
    {
        'slug': 'sum-of-even-indices',
        'title': 'Сумма элементов на четных позициях',
        'desc': 'Напишите функцию `solution(nums)`, находящую сумму элементов с четными индексами (`0, 2, 4, ...`).\n\n### Пример:\n* Вход: `[2, 3, 4, 5]` ➔ Результат: `6` (2 + 4)',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays', 'basics'],
        'fn': lambda nums: sum(nums[::2]),
        'tests': [([2, 3, 4, 5],), ([10],), ([],), ([1, 2, 1, 2, 1],)],
    },
    {
        'slug': 'is-isogram',
        'title': 'Проверка на изограмму',
        'desc': 'Изограмма — это слово без повторяющихся букв. Напишите функцию `solution(s)`, возвращающую `True`, если слово — изограмма (регистр игнорируется), и `False` иначе.\n\n### Пример:\n* Вход: `"Dermatoglyphics"` ➔ Результат: `True`\n* Вход: `"aba"` ➔ Результат: `False`',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: len(s) == len(set(s.lower())),
        'tests': [("Dermatoglyphics",), ("aba",), ("moOse",), ("",), ("isogram",)],
    },
    {
        'slug': 'list-chunk-pairs',
        'title': 'Разбиение списка на пары',
        'desc': 'Напишите функцию `solution(lst)`, разбивающую список на пары соседних элементов (списки по 2 элемента). Если длина нечетная, последний элемент остается один в списке.\n\n### Пример:\n* Вход: `[1, 2, 3, 4, 5]` ➔ Результат: `[[1, 2], [3, 4], [5]]`',
        'starter': 'def solution(lst):\n    pass',
        'tags': ['arrays'],
        'fn': lambda lst: [lst[i:i+2] for i in range(0, len(lst), 2)],
        'tests': [([1, 2, 3, 4, 5],), ([1, 2, 3, 4],), ([],), ([42],)],
    },
    {
        'slug': 'square-digits-of-number',
        'title': 'Возведение каждой цифры в квадрат',
        'desc': 'Напишите функцию `solution(num)`, которая возводит в квадрат каждую цифру числа и конкатенирует их.\n\n### Пример:\n* Вход: `9119` ➔ Результат: `811181` (9^2=81, 1^2=1, 1^2=1, 9^2=81)',
        'starter': 'def solution(num):\n    pass',
        'tags': ['math'],
        'fn': lambda num: int(''.join(str(int(d)**2) for d in str(num))),
        'tests': [(9119,), (0,), (123,), (765,)],
    },
    {
        'slug': 'find-the-stray-number',
        'title': 'Поиск одиночного числа',
        'desc': 'Вам дан нечетный список чисел, где все числа одинаковы, кроме одного. Напишите функцию `solution(nums)`, находящую это единственное отличающееся число.\n\n### Пример:\n* Вход: `[1, 1, 2]` ➔ Результат: `2`\n* Вход: `[17, 17, 3, 17, 17]` ➔ Результат: `3`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums: min(set(nums), key=nums.count),
        'tests': [([1, 1, 2],), ([17, 17, 3, 17, 17],), ([0, 0, 0, 7, 0],)],
    },
    {
        'slug': 'flatten-shallow-list',
        'title': 'Выравнивание списка списков',
        'desc': 'Напишите функцию `solution(lst_of_lsts)`, которая принимает список списков и объединяет их в один плоский список.\n\n### Пример:\n* Вход: `[[1, 2], [3], [4, 5]]` ➔ Результат: `[1, 2, 3, 4, 5]`',
        'starter': 'def solution(lst_of_lsts):\n    pass',
        'tags': ['arrays'],
        'fn': lambda lsts: [item for sub in lsts for item in sub],
        'tests': [([[1, 2], [3], [4, 5]],), ([[], [1]],), ([],)],
    },
    {
        'slug': 'alphabetical-character-position',
        'title': 'Позиция буквы в алфавите',
        'desc': 'Напишите функцию `solution(char)`, возвращающую порядковый номер английской буквы в алфавите от 1 до 26 (без учета регистра).\n\n### Пример:\n* Вход: `"a"` ➔ Результат: `1`\n* Вход: `"Z"` ➔ Результат: `26`',
        'starter': 'def solution(char):\n    pass',
        'tags': ['strings'],
        'fn': lambda c: ord(c.lower()) - ord('a') + 1,
        'tests': [("a",), ("z",), ("B",), ("M",)],
    },
    {
        'slug': 'count-divisors-of-number',
        'title': 'Количество делителей числа',
        'desc': 'Напишите функцию `solution(n)`, возвращающую количество натуральных делителей числа `n`.\n\n### Пример:\n* Вход: `12` ➔ Результат: `6` (1, 2, 3, 4, 6, 12)',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math'],
        'fn': lambda n: sum(1 for i in range(1, n + 1) if n % i == 0),
        'tests': [(12,), (30,), (7,), (1,), (16,)],
    },
    {
        'slug': 'multiplication-table-single',
        'title': 'Строка таблицы умножения',
        'desc': 'Напишите функцию `solution(n)`, возвращающую список из первых 10 произведений числа `n` (`[n*1, n*2, ..., n*10]`).\n\n### Пример:\n* Вход: `5` ➔ Результат: `[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math', 'basics'],
        'fn': lambda n: [n * i for i in range(1, 11)],
        'tests': [(5,), (1,), (10,), (0,)],
    },
    {
        'slug': 'remove-minimum-element',
        'title': 'Удаление наименьшего элемента',
        'desc': 'Напишите функцию `solution(nums)`, которая удаляет первое вхождение минимального элемента из списка и возвращает новый список.\n\n### Пример:\n* Вход: `[1, 2, 3, 4, 5]` ➔ Результат: `[2, 3, 4, 5]`\n* Вход: `[5, 3, 2, 1, 4]` ➔ Результат: `[5, 3, 2, 4]`',
        'starter': 'def solution(nums):\n    pass',
        'tags': ['arrays'],
        'fn': lambda nums: [x for i, x in enumerate(nums) if i != nums.index(min(nums))] if nums else [],
        'tests': [([1, 2, 3, 4, 5],), ([5, 3, 2, 1, 4],), ([2, 2, 1, 2, 1],), ([],)],
    },
    {
        'slug': 'find-multiples-of-number',
        'title': 'Кратные числа до предела',
        'desc': 'Напишите функцию `solution(integer, limit)`, возвращающую список всех чисел, кратных `integer`, не превышающих `limit`.\n\n### Пример:\n* Вход: `5, 25` ➔ Результат: `[5, 10, 15, 20, 25]`',
        'starter': 'def solution(integer, limit):\n    pass',
        'tags': ['math'],
        'fn': lambda int_val, lim: list(range(int_val, lim + 1, int_val)),
        'tests': [(5, 25), (1, 10), (5, 7), (4, 27)],
    },
    {
        'slug': 'greet-user-by-name',
        'title': 'Форматирование приветствия',
        'desc': 'Напишите функцию `solution(name)`, возвращающую приветствие `"Hello, <Name>!"`, где имя начинается с заглавной буквы, а остальные буквы строчные.\n\n### Пример:\n* Вход: `"aLICE"` ➔ Результат: `"Hello, Alice!"`',
        'starter': 'def solution(name):\n    pass',
        'tags': ['strings', 'basics'],
        'fn': lambda name: f"Hello, {name.capitalize()}!",
        'tests': [("aLICE",), ("BOB",), ("john",), ("x",)],
    },
    {
        'slug': 'binary-representation-ones',
        'title': 'Количество единиц в двоичной записи',
        'desc': 'Напишите функцию `solution(n)`, возвращающую количество единиц в двоичном представлении целого положительного числа `n`.\n\n### Пример:\n* Вход: `1234` (10011010010_2) ➔ Результат: `5`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math'],
        'fn': lambda n: bin(n).count('1'),
        'tests': [(1234,), (0,), (7,), (1024,), (15,)],
    },
    {
        'slug': 'round-to-next-multiple-of-5',
        'title': 'Округление вверх до кратного 5',
        'desc': 'Напишите функцию `solution(n)`, округляющую число `n` до ближайшего числа, кратного 5, которое `>= n`.\n\n### Пример:\n* Вход: `3` ➔ Результат: `5`\n* Вход: `15` ➔ Результат: `15`\n* Вход: `21` ➔ Результат: `25`',
        'starter': 'def solution(n):\n    pass',
        'tags': ['math'],
        'fn': lambda n: ((n + 4) // 5) * 5 if n >= 0 else (n // 5) * 5,
        'tests': [(3,), (15,), (21,), (0,), (33,)],
    },
    {
        'slug': 'disemvowel-trolls',
        'title': 'Анти-тролль: удаление гласных из комментария',
        'desc': 'Напишите функцию `solution(string)`, которая принимает строку и возвращает новую строку без гласных букв (как строчных, так и заглавных).\n\n### Пример:\n* Вход: `"This is a test!"` ➔ Результат: `"Ths s  tst!"`',
        'starter': 'def solution(string):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: ''.join(c for c in s if c not in 'aeiouAEIOU'),
        'tests': [("This is a test!",), ("No offense but, Your writing is among the worst",), ("",)],
    },
    {
        'slug': 'filter-list-strings-out',
        'title': 'Фильтрация строк из смешанного списка',
        'desc': 'Напишите функцию `solution(lst)`, которая принимает список чисел и строк и возвращает новый список, содержащий только целые числа.\n\n### Пример:\n* Вход: `[1, 2, "a", "b", 0, 15]` ➔ Результат: `[1, 2, 0, 15]`',
        'starter': 'def solution(lst):\n    pass',
        'tags': ['arrays'],
        'fn': lambda lst: [x for x in lst if isinstance(x, int) and not isinstance(x, bool)],
        'tests': [([1, 2, "a", "b", 0, 15],), ([1, "a", "b", 0, 15],), (["x", "y"],)],
    },
    {
        'slug': 'shortest-word-in-string',
        'title': 'Длина самого короткого слова',
        'desc': 'Напишите функцию `solution(s)`, которая принимает строку слов, разделенных пробелами, и возвращает длину самого короткого слова.\n\n### Пример:\n* Вход: `"bitcoin take over the world"` ➔ Результат: `3` ("the")',
        'starter': 'def solution(s):\n    pass',
        'tags': ['strings'],
        'fn': lambda s: min(len(w) for w in s.split()),
        'tests': [("bitcoin take over the world",), ("Let's travel abroad shall we",), ("one",)],
    },
]

# Проверка количества задач
print(f"Total easy tasks in file: {len(EASY_TASKS)}")
