# Generated by Django 5.2.17 on 2026-09-01 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задачи')),
                ('slug', models.SlugField(max_length=255, unique=True, verbose_name='URL-слаг')),
                ('description', models.TextField(verbose_name='Описание задачи (Markdown)')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy (8-7 kyu)'), ('medium', 'Medium (6-4 kyu)'), ('hard', 'Hard (3-1 kyu)')], default='easy', max_length=10, verbose_name='Сложность')),
                ('starter_code', models.TextField(default='def solution():\n    pass', verbose_name='Начальный шаблон кода')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(verbose_name='Отправленный код')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('passed', 'Пройдено'), ('failed', 'Ошибка в тестах'), ('error', 'Ошибка выполнения (Runtime Error)'), ('timeout', 'Превышено время ожидания')], default='pending', max_length=10, verbose_name='Статус')),
                ('execution_time', models.FloatField(blank=True, null=True, verbose_name='Время выполнения (сек)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='challenges.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Отправленное решение',
                'verbose_name_plural': 'Отправленные решения',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField(verbose_name='Входные данные')),
                ('expected_output', models.TextField(verbose_name='Ожидаемый результат')),
                ('is_hidden', models.BooleanField(default=False, verbose_name='Скрытый тест?')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='challenges.task', verbose_name='Задача')),
            ],
            options={
                'verbose_name': 'Тест-кейс',
                'verbose_name_plural': 'Тест-кейсы',
            },
        ),
    ]
