# Generated by Django 5.2.17 on 2026-09-04 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_tag_task_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дедлайн сдачи'),
        ),
        migrations.CreateModel(
            name='CodeBattle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('waiting', 'Ожидание соперника'), ('in_progress', 'Идет битва'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], default='waiting', max_length=15, verbose_name='Статус')),
                ('creator_code', models.TextField(blank=True, default='', verbose_name='Код создателя')),
                ('opponent_code', models.TextField(blank=True, default='', verbose_name='Код соперника')),
                ('creator_passed', models.BooleanField(default=False, verbose_name='Создатель прошел тесты')),
                ('opponent_passed', models.BooleanField(default=False, verbose_name='Соперник прошел тесты')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Время старта')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_battles', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('opponent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='joined_battles', to=settings.AUTH_USER_MODEL, verbose_name='Соперник')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='challenges.task', verbose_name='Задача')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_battles', to=settings.AUTH_USER_MODEL, verbose_name='Победитель')),
            ],
            options={
                'verbose_name': 'Code Battle Дуэль',
                'verbose_name_plural': 'Code Battle Дуэли',
                'ordering': ['-created_at'],
            },
        ),
    ]
