# Generated by Django 5.2.17 on 2026-09-09 07:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_assignment_due_date_codebattle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reference_solution',
            field=models.TextField(blank=True, default='', verbose_name='Эталонное решение'),
        ),
        migrations.AddField(
            model_name='task',
            name='reference_solution_explanation',
            field=models.TextField(blank=True, default='', verbose_name='Пояснение к эталонному решению'),
        ),
        migrations.CreateModel(
            name='TaskSolutionView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время просмотра')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_views', to='challenges.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_views', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Просмотр решения задачи',
                'verbose_name_plural': 'Просмотры решений задач',
                'unique_together': {('user', 'task')},
            },
        ),
    ]
