# Generated by Django 5.2.17 on 2026-09-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_task_reference_solution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codebattle',
            name='status',
            field=models.CharField(choices=[('waiting', 'Ожидание соперника'), ('in_progress', 'Идет битва'), ('finished', 'Завершена'), ('cancelled', 'Отменена')], db_index=True, default='waiting', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('pending', 'В очереди'), ('passed', 'Пройдено'), ('failed', 'Ошибка в тестах'), ('error', 'Ошибка выполнения (Runtime Error)'), ('timeout', 'Превышено время ожидания')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
